### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by Bewelge** [Aubind97/midiano#1]
Hey there,

very nice project you've created :-)

However I have been developing a similar app with the same name ( https://github.com/Bewelge/MIDIano ) and have had it published for quite some time. That's why I'd like to ask you not to use the name "Midiano" in the future and rename this repository and your website.

Thanks for your understanding and sorry for the inconvenience.

**Comment by Aubind97** [comment]
That's it!
Sorry, I didn't notice that an identical project existed.

**Comment by Bewelge** [comment]
No worries :-)
Thanks for reacting so quickly!
